"""Yunshu L4 Engine — continuous batching inference."""

__all__ = [
    "BatchedEngine",
    "Engine",
    "EngineConfig",
    "GenerationOutput",
    "RequestOutput",
    "RequestState",
]


def __getattr__(name):
    """Lazy imports for heavy modules — only loaded when accessed."""
    _lazy = {
        "BatchedEngine": ".batched_engine",
        "Engine": ".engine",
        "EngineConfig": ".engine",
        "GenerationOutput": ".batched_engine",
        "RequestOutput": ".request",
        "RequestState": ".engine",
        "AsyncEngineCore": ".engine_core",
        "EngineCore": ".engine_core",
        "EngineCoreConfig": ".engine_core",
        "ExternalPrefiller": ".external_prefill",
        "PrefillResult": ".external_prefill",
        "PrefillAbortedError": ".external_prefill",
        "check_abort": ".external_prefill",
        "ConstrainedSampler": ".json_schema",
        "JsonSchemaConstraint": ".json_schema",
        "JsonState": ".json_schema",
        "apply_json_constraint": ".json_schema",
        "make_constrained_sampler": ".json_schema",
        "KVOffloadConfig": ".kv_offload",
        "KVOffloadManager": ".kv_offload",
        "OffloadPolicy": ".kv_offload",
        "ThresholdPolicy": ".kv_offload",
        "LRUPolicy": ".kv_offload",
        "PriorityPolicy": ".kv_offload",
        "OffloadRequest": ".kv_offload",
        "OffloadResult": ".kv_offload",
        "ModelManager": ".model_manager",
        "ModelType": ".model_manager",
        "RequestOutputCollector": ".output_collector",
        "RequestStreamState": ".output_collector",
        "Request": ".request",
        "RequestOutputNew": ".request",
        "RequestStatus": ".request",
        "SamplingParams": ".request",
        "Scheduler": ".scheduler",
        "SchedulerConfig": ".scheduler",
        "SchedulerOutput": ".scheduler",
        "SpecHeadInfo": ".speculative_decoder",
        "SpecDecodingConfig": ".speculative_decoder",
        "auto_configure_speculative": ".speculative_decoder",
        "detect_spec_heads": ".speculative_decoder",
        "EncoderCacheManager": ".encoder_cache",
        "EncoderCacheEntry": ".encoder_cache",
        "GrammarBitmaskEngine": ".grammar_bitmask",
        "BitmaskApplicator": ".grammar_bitmask",
        "BitmaskConstrainedSampler": ".grammar_bitmask",
        "TokenStringTable": ".grammar_bitmask",
        "build_bitmask_engine": ".grammar_bitmask",
        "is_bitmask_enabled": ".grammar_bitmask",
        # KV Transfer Protocol (disaggregated prefill)
        "KVTransferConfig": ".kv_transfer",
        "KVTransferProtocol": ".kv_transfer",
        "KVTransferClient": ".kv_transfer",
        "KVTransferServer": ".kv_transfer",
        "KVTransferStats": ".kv_transfer",
        "KVTransferResult": ".kv_transfer",
        "KVTransferHeader": ".kv_transfer",
        "KVTransferMessage": ".kv_transfer",
        "KVBlockData": ".kv_transfer",
        "CompressionType": ".kv_transfer",
        "TransferStatus": ".kv_transfer",
        "is_kv_transfer_enabled": ".kv_transfer",
        "create_transfer_client": ".kv_transfer",
        "create_transfer_server": ".kv_transfer",
        # Streaming Optimizer (C18 GPU/CPU overlap)
    "TokenPipeline": ".streaming_optimizer",
    "PipelineConfig": ".streaming_optimizer",
    "PipelineStage": ".streaming_optimizer",
    "PipelineToken": ".streaming_optimizer",
    "PrefetchSampler": ".streaming_optimizer",
    "SamplingPlan": ".streaming_optimizer",
    "BatchedDetokenizer": ".streaming_optimizer",
    "StreamingBackpressureController": ".streaming_optimizer",
    "BackpressureConfig": ".streaming_optimizer",
    # Checkpoint / Restore (fault recovery)
    "InferenceCheckpoint": ".checkpoint",
    "InferenceState": ".checkpoint",
    "AutoCheckpointPolicy": ".checkpoint",
    "FaultRecoveryManager": ".checkpoint",
    "RecoveryStrategy": ".checkpoint",
    "RecoveryResult": ".checkpoint",
    "ProgressEstimator": ".checkpoint",
    "ProgressInfo": ".checkpoint",
    # Mamba / Hybrid KV Cache (§12.2)
        "CacheBlockType": ".mamba_cache",
        "HybridKVCache": ".mamba_cache",
        "MambaSSMState": ".mamba_cache",
        "BlockAlignedCacheSplitter": ".mamba_cache",
        "LayerGroup": ".mamba_cache",
        "CachePoolStats": ".mamba_cache",
    # Scheduler Mixins (§14.1 SGLang pattern)
    "SchedulerMixin": ".scheduler_mixins",
    "MetricsMixin": ".scheduler_mixins",
    "ProfilingMixin": ".scheduler_mixins",
    "DisaggregationMixin": ".scheduler_mixins",
    "DataParallelMixin": ".scheduler_mixins",
    "PipelineParallelMixin": ".scheduler_mixins",
    "SpecDecodeMixin": ".scheduler_mixins",
    "MemoryPressureMixin": ".scheduler_mixins",
    "CompositionScheduler": ".scheduler_mixins",
    # Forward Batch (§14.1 vLLM/SGLang 3-level batch)
    "RequestSlot": ".forward_batch",
    "ScheduleBatch": ".forward_batch",
    "ForwardBatch": ".forward_batch",
    "BatchResult": ".forward_batch",
    "BatchComposer": ".forward_batch",
    # Request Lifecycle (state machine + adaptive concurrency)
    "RequestPhase": ".request_lifecycle",
    "RequestLifecycleState": ".request_lifecycle",
    "AdaptiveConcurrencyController": ".request_lifecycle",
    "RequestLifecycleOrchestrator": ".request_lifecycle",
    # Model Preprocessors (§16.5 vllm-omni pattern)
    "PreprocessorRegistry": ".model_preprocessor",
    "PreprocessedInput": ".model_preprocessor",
    # KV Lifecycle (unified tier management)
    "KVLifecycleManager": ".kv_lifecycle",
    "KVBlock": ".kv_lifecycle",
    "KVTier": ".kv_lifecycle",
    "KVTierConfig": ".kv_lifecycle",
    "CacheWarmingPredictor": ".kv_lifecycle",
    "KVCompactionScheduler": ".kv_lifecycle",
    # Inference Budget (token/time/cost enforcement)
    "InferenceBudget": ".inference_budget",
    "InferenceBudgetManager": ".inference_budget",
    # Request Deduplication (SGLang pattern)
    "RequestDeduplicator": ".request_dedup",
    "DeduplicationEntry": ".request_dedup",
    }
    if name in _lazy:
        import importlib
        module = importlib.import_module(_lazy[name], __name__)
        return getattr(module, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
