"""Generate docs/CONFIGURATION.md from the settings registry.

uv run python scripts/gen_config_docs.py          # write the file
uv run python scripts/gen_config_docs.py --check  # exit 1 if out of date
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

from yunshu_engine.settings import CATEGORIES, MAX_EXPERIMENTAL, REGISTRY  # noqa: E402

OUT = ROOT / "docs" / "CONFIGURATION.md"

INTRO = f"""# Configuration

<!-- Generated by scripts/gen_config_docs.py from python/yunshu_engine/settings.py. Do not edit by hand. -->

Every Yunshu setting is a `YUNSHU_*` name registered in
`python/yunshu_engine/settings.py`, with one type, one default and one parse
rule. Nothing else reads `YUNSHU_*` environment variables.

## Where values come from

Highest precedence first:

1. `yunshu serve` flags and `--set KEY=VALUE` (repeatable; `KEY` with or
   without the `YUNSHU_` prefix, e.g. `--set mtp_block_size=4`),
2. the process environment,
3. a TOML config file: `yunshu serve --config yunshu.toml` or
   `YUNSHU_CONFIG=yunshu.toml`,
4. the default listed below.

The config file holds `KEY = value` pairs, flat or grouped under any tables
(table names are ignored; keys may be short or full names):

```toml
model = "~/models/Qwen3.8-27B-4bit"

[server]
default_max_tokens = 1024

[voice]
YUNSHU_REALTIME_SILENCE_MS = 400
```

Booleans accept `1/true/yes/on` and `0/false/no/off`. A value that does not
parse is a startup error listing every bad setting. A `YUNSHU_*` name that is
not registered is ignored with a warning naming the closest registered
setting.

`yunshu config` prints the effective value of every stable setting and its
source (`cli`, `env`, `file`, `default`); `--all` adds experimental and
internal ones, `--json` prints JSON, `--config FILE` includes a config file.

## Stability

- **stable**: supported deployment settings.
- **experimental**: temporary. Each names the measurement that decides it and
  when it was added; once measured, the winner becomes the default and the
  flag and losing code path are deleted. At most {MAX_EXPERIMENTAL} exist at a time.
- **internal**: debugging aids.
"""


def _default(s) -> str:
    if s.default is None or s.default == "" or s.default == ():
        return "unset"
    if isinstance(s.default, bool):
        return "on" if s.default else "off"
    if (
        isinstance(s.default, int)
        and s.default >= 1024 * 1024
        and s.default % (1024 * 1024) == 0
    ):
        return f"{s.default} ({s.default // (1024 * 1024)} MiB)"
    return str(s.default)


def _type(s) -> str:
    if s.type == "enum":
        return " \\| ".join(f"`{c}`" if c else "`''`" for c in s.choices)
    return s.type


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def render() -> str:
    out = [INTRO]
    stable = [s for s in REGISTRY.values() if s.stability == "stable"]
    out.append("## Stable settings\n")
    for cat in CATEGORIES:
        rows = [s for s in stable if s.category == cat]
        if not rows:
            continue
        out.append(f"### {cat}\n")
        out.append("| Setting | Type | Default | Description |")
        out.append("|---|---|---|---|")
        for s in rows:
            out.append(
                f"| `{s.name}` | {_type(s)} | {_cell(_default(s))} | {_cell(s.description)} |"
            )
        out.append("")
    for stability, title in (
        ("experimental", "Experimental settings"),
        ("internal", "Internal settings"),
    ):
        rows = [s for s in REGISTRY.values() if s.stability == stability]
        out.append(f"## {title}\n")
        if not rows:
            out.append("None.\n")
            continue
        if stability == "experimental":
            out.append(
                "| Setting | Type | Default | Description | Decided by | Added |"
            )
            out.append("|---|---|---|---|---|---|")
            for s in rows:
                out.append(
                    f"| `{s.name}` | {_type(s)} | {_cell(_default(s))} | {_cell(s.description)} "
                    f"| {_cell(s.decide)} | {s.added} |"
                )
        else:
            out.append("| Setting | Type | Default | Description |")
            out.append("|---|---|---|---|")
            for s in rows:
                out.append(
                    f"| `{s.name}` | {_type(s)} | {_cell(_default(s))} | {_cell(s.description)} |"
                )
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(
                f"{OUT.relative_to(ROOT)} is out of date; run scripts/gen_config_docs.py"
            )
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
